# Generated by Buildr 1.4.4, change to your liking
# Standard maven2 repository
repositories.remote << 'http://www.ibiblio.org/maven2'

desc 'shellwrapper'
define 'shellwrapper' do
  project.group = 'de.entwicklerland'
  project.version = '0.2'
  package :jar, :id => 'shellwrapper'
end
